export const SKU_LIST = [
  {
    id: '494556029067198468',
    productId: '423536442087833615',
    portId: '193815923449200000',
    portName: 'Singapore',
    markupRate: 10,
    price: 11.11,
    title: 'Small/Med_50g_Singapore_Bag',
    cost: 10,
    displayInMol: false,
    costCurrency: 'USD',
    createBy: 'liqi',
    priceType: 'FIXED',
    uom: 'Bag',
    specs: [
      {
        id: '0_1',
        priceId: '494556029067198468',
        specName: 'Port',
        specId: '0_1',
        itemName: 'Singapore',
        specItemId: '0_1_1',
      },
      {
        id: '0_2',
        priceId: '494556029067198468',
        specName: 'UOM',
        specId: '0_2',
        itemName: 'Bag',
        specItemId: '0_2',
      },
      {
        id: '3',
        priceId: '494556029067198468',
        specName: 'Specification',
        specId: '1',
        itemName: 'Small/Med',
        specItemId: '1',
      },
      {
        id: '4',
        priceId: '494556029067198468',
        specName: 'Weight',
        specId: '2',
        itemName: '50g',
        specItemId: '4',
      },
    ],
  },
  {
    id: '494556029067198467',
    productId: '423536442087833615',
    portId: '193815923449200000',
    portName: 'Dalian',
    markupRate: 10,
    price: 22.22,
    title: 'Small/Med_20g_Dalian_Bag', // TODO 需要新增
    priceCurrency: '',
    cost: 20,
    displayInMol: false,
    costCurrency: 'USD',
    createBy: 'liqi',
    createTime: 1597716654000,
    updateBy: '',
    updateTime: 1597716661000,
    priceType: 'FIXED',
    uom: 'Bag',
    specs: [
      {
        id: '0_1',
        priceId: '494556029067198468',
        specName: 'Port',
        specId: '0_1',
        itemName: 'Dalian',
        specItemId: '0_1_2',
      },
      {
        id: '0_2',
        priceId: '494556029067198468',
        specName: 'UOM',
        specId: '0_2',
        itemName: 'Bag',
        specItemId: '0_2',
      },
      {
        id: '1',
        priceId: '494556029067198467',
        specName: 'Specification',
        specId: '1',
        itemName: 'Small/Med',
        specItemId: '1',
      },
      {
        id: '2',
        priceId: '494556029067198467',
        specName: 'Weight', // key
        specId: '2', // key_id
        itemName: '20g', // value
        specItemId: '3', // value_id
      },
    ],
  },
]

export const SKU_LIST_OLD = [
  {
    id: 2,
    price: 77.76,
    discount_price: null,
    online: true,
    img: '',
    title: '金属灰.七龙珠.小号 S',
    spu_id: 2,
    category_id: 17,
    root_category_id: 3,
    specs: [
      {
        key_id: 1,
        key: '颜色',
        value_id: 45,
        value: '金属灰',
      },
      {
        key_id: 3,
        key: '图案',
        value_id: 9,
        value: '七龙珠',
      },
      {
        key_id: 4,
        key: '尺码',
        value_id: 14,
        value: '小号 S',
      },
    ],
    code: '2$1-45#3-9#4-14',
    stock: 5,
  },
  {
    id: 3,
    price: 66,
    discount_price: 59,
    online: true,
    img: '',
    title: '青芒色.灌篮高手.中号 M',
    spu_id: 2,
    category_id: 17,
    root_category_id: 3,
    specs: [
      {
        key_id: 1,
        key: '颜色',
        value_id: 42,
        value: '青芒色',
      },
      {
        key_id: 3,
        key: '图案',
        value_id: 10,
        value: '灌篮高手',
      },
      {
        key_id: 4,
        key: '尺码',
        value_id: 15,
        value: '中号 M',
      },
    ],
    code: '2$1-42#3-10#4-15',
    stock: 999,
  },
  {
    id: 3,
    price: 66,
    discount_price: 59,
    online: true,
    img: '',
    title: '橘黄色.灌篮高手.中号 M',
    spu_id: 2,
    category_id: 17,
    root_category_id: 3,
    specs: [
      {
        key_id: 1,
        key: '颜色',
        value_id: 44,
        value: '橘黄色',
      },
      {
        key_id: 3,
        key: '图案',
        value_id: 10,
        value: '灌篮高手',
      },
      {
        key_id: 4,
        key: '尺码',
        value_id: 15,
        value: '中号 M',
      },
    ],
    code: '2$1-42#3-10#4-15',
    stock: 999,
  },
  {
    id: 4,
    price: 88,
    discount_price: null,
    online: true,
    img: '',
    title: '青芒色.圣斗士.大号  L',
    spu_id: 2,
    category_id: 17,
    root_category_id: 3,
    specs: [
      {
        key_id: 1,
        key: '颜色',
        value_id: 42,
        value: '青芒色',
      },
      {
        key_id: 3,
        key: '图案',
        value_id: 11,
        value: '圣斗士',
      },
      {
        key_id: 4,
        key: '尺码',
        value_id: 16,
        value: '大号  L',
      },
    ],
    code: '2$1-42#3-11#4-16',
    stock: 8,
  },
  {
    id: 5,
    price: 77,
    discount_price: 59,
    online: true,
    img:
      'http://i1.sleeve.7yue.pro/assets/09f32ac8-1af4-4424-b221-44b10bd0986e.png',
    title: '橘黄色.七龙珠.小号 S',
    spu_id: 2,
    category_id: 17,
    root_category_id: 3,
    specs: [
      {
        key_id: 1,
        key: '颜色',
        value_id: 44,
        value: '橘黄色',
      },
      {
        key_id: 3,
        key: '图案',
        value_id: 9,
        value: '七龙珠',
      },
      {
        key_id: 4,
        key: '尺码',
        value_id: 14,
        value: '小号 S',
      },
    ],
    code: '2$1-44#3-9#4-14',
    stock: 7,
  },
]
